source 'https://rubygems.org'

gem 'jquery-rails'
gem 'quiet_assets'
gem 'rails', '3.2.13'
gem 'sqlite3'

group :test, :development do
	gem 'better_errors'
    gem 'debugger'
    gem 'thin'
end

group :test do
	gem 'factory_girl_rails'
	gem 'minitest-rails'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

platforms :ruby do # linux
  gem 'unicorn'
end

platforms :mswin do
  # gems specific to windows
end

group :production do
	#gem 'unicorn'
end